/* The following code was generated by JFlex 1.6.1 */

package atividade1;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/main/resources/exemplo.jflex</tt>
 */
public class Minijava {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\4\1\3\1\3\22\0\1\1\1\44\4\0"+
    "\1\41\1\0\2\11\1\5\1\45\1\11\1\46\1\11\1\2\1\10"+
    "\11\7\1\0\1\11\1\42\1\43\3\0\22\6\1\32\7\6\1\11"+
    "\1\0\1\11\1\0\1\6\1\0\1\16\1\12\1\20\1\27\1\15"+
    "\1\37\1\34\1\36\1\24\2\6\1\14\1\31\1\17\1\13\1\22"+
    "\1\6\1\33\1\21\1\26\1\23\1\30\1\35\1\25\1\40\1\6"+
    "\1\11\1\11\1\11\7\0\1\4\u1fa2\0\1\4\1\4\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\2\6"+
    "\1\7\17\5\1\1\1\10\1\7\1\11\1\12\1\13"+
    "\1\2\1\0\11\5\1\14\11\5\1\15\1\16\1\17"+
    "\1\0\4\5\1\20\3\5\1\21\13\5\1\22\4\5"+
    "\1\23\1\24\1\25\1\26\10\5\1\27\5\5\1\30"+
    "\1\31\1\5\1\32\1\5\1\33\1\34\1\35\1\5"+
    "\1\36\1\37\1\40\1\0\1\5\1\0\1\5\1\0"+
    "\1\5\1\0\1\5\1\0\1\5\1\0\1\5\1\0"+
    "\1\5\1\0\1\5\1\0\1\5\1\0\1\5\1\0"+
    "\1\5\2\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\47\0\116\0\47\0\47\0\165\0\234"+
    "\0\47\0\47\0\303\0\352\0\u0111\0\u0138\0\u015f\0\u0186"+
    "\0\u01ad\0\u01d4\0\u01fb\0\u0222\0\u0249\0\u0270\0\u0297\0\u02be"+
    "\0\u02e5\0\u030c\0\47\0\u0333\0\u035a\0\47\0\47\0\u0381"+
    "\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444\0\u046b\0\u0492\0\u04b9"+
    "\0\u04e0\0\u0507\0\165\0\u052e\0\u0555\0\u057c\0\u05a3\0\u05ca"+
    "\0\u05f1\0\u0618\0\u063f\0\u0666\0\47\0\47\0\47\0\u068d"+
    "\0\u06b4\0\u06db\0\u0702\0\u0729\0\165\0\u0750\0\u0777\0\u079e"+
    "\0\165\0\u07c5\0\u07ec\0\u0813\0\u083a\0\u0861\0\u0888\0\u08af"+
    "\0\u08d6\0\u08fd\0\u0924\0\u094b\0\165\0\u0972\0\u0999\0\u09c0"+
    "\0\u09e7\0\165\0\165\0\165\0\165\0\u0a0e\0\u0a35\0\u0a5c"+
    "\0\u0a83\0\u0aaa\0\u0ad1\0\u0af8\0\u0b1f\0\165\0\u0b46\0\u0b6d"+
    "\0\u0b94\0\u0bbb\0\u0be2\0\165\0\165\0\u0c09\0\165\0\u0c30"+
    "\0\165\0\165\0\165\0\u0c57\0\165\0\165\0\165\0\u0c7e"+
    "\0\u0ca5\0\u0ccc\0\u0cf3\0\u0d1a\0\u0d41\0\u0d68\0\u0d8f\0\u0db6"+
    "\0\u0ddd\0\u0e04\0\u0e2b\0\u0e52\0\u0e79\0\u0ea0\0\u0ec7\0\u0eee"+
    "\0\u0f15\0\u0f3c\0\u0f63\0\u0f8a\0\u0fb1\0\47\0\165";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\7\1\14\1\15\1\7\1\16"+
    "\1\17\1\20\1\21\1\7\1\22\1\7\1\23\1\7"+
    "\1\24\1\25\1\26\1\27\1\7\1\30\1\7\1\31"+
    "\1\7\1\32\1\33\1\34\1\35\1\36\1\37\51\0"+
    "\1\40\2\0\1\41\47\0\3\7\1\0\27\7\15\0"+
    "\2\10\44\0\3\7\1\0\1\7\1\42\25\7\14\0"+
    "\3\7\1\0\3\7\1\43\23\7\14\0\3\7\1\0"+
    "\2\7\1\44\10\7\1\45\13\7\14\0\3\7\1\0"+
    "\3\7\1\46\23\7\14\0\3\7\1\0\2\7\1\47"+
    "\24\7\14\0\3\7\1\0\14\7\1\50\12\7\14\0"+
    "\3\7\1\0\11\7\1\51\15\7\14\0\3\7\1\0"+
    "\5\7\1\52\17\7\1\53\1\7\14\0\3\7\1\0"+
    "\21\7\1\54\2\7\1\55\2\7\14\0\3\7\1\0"+
    "\1\7\1\56\25\7\14\0\3\7\1\0\4\7\1\57"+
    "\22\7\14\0\3\7\1\0\14\7\1\60\11\7\1\61"+
    "\14\0\3\7\1\0\3\7\1\62\23\7\14\0\3\7"+
    "\1\0\24\7\1\63\2\7\14\0\3\7\1\0\4\7"+
    "\1\64\22\7\47\0\1\65\50\0\1\66\46\0\1\67"+
    "\3\0\3\40\2\0\42\40\5\41\1\70\41\41\6\0"+
    "\3\7\1\0\1\7\1\71\25\7\14\0\3\7\1\0"+
    "\5\7\1\72\21\7\14\0\3\7\1\0\7\7\1\73"+
    "\17\7\14\0\3\7\1\0\14\7\1\74\12\7\14\0"+
    "\3\7\1\0\23\7\1\75\3\7\14\0\3\7\1\0"+
    "\4\7\1\76\22\7\14\0\3\7\1\0\4\7\1\77"+
    "\22\7\14\0\3\7\1\0\1\100\26\7\14\0\3\7"+
    "\1\0\14\7\1\101\12\7\14\0\3\7\1\0\11\7"+
    "\1\102\15\7\14\0\3\7\1\0\12\7\1\103\14\7"+
    "\14\0\3\7\1\0\12\7\1\104\14\7\14\0\3\7"+
    "\1\0\12\7\1\105\14\7\14\0\3\7\1\0\21\7"+
    "\1\106\5\7\14\0\3\7\1\0\7\7\1\107\17\7"+
    "\14\0\3\7\1\0\14\7\1\110\12\7\14\0\3\7"+
    "\1\0\12\7\1\111\14\7\14\0\3\7\1\0\2\7"+
    "\1\112\24\7\6\0\2\41\1\3\2\41\1\70\41\41"+
    "\6\0\3\7\1\0\2\7\1\113\24\7\14\0\3\7"+
    "\1\0\22\7\1\114\4\7\14\0\3\7\1\0\3\7"+
    "\1\115\23\7\14\0\3\7\1\0\3\7\1\116\23\7"+
    "\14\0\3\7\1\0\7\7\1\117\17\7\14\0\3\7"+
    "\1\0\14\7\1\120\12\7\14\0\3\7\1\0\2\7"+
    "\1\121\24\7\14\0\3\7\1\0\3\7\1\122\23\7"+
    "\14\0\3\7\1\0\7\7\1\123\17\7\14\0\3\7"+
    "\1\0\15\7\1\124\11\7\14\0\3\7\1\0\5\7"+
    "\1\125\21\7\14\0\3\7\1\0\12\7\1\126\14\7"+
    "\14\0\3\7\1\0\14\7\1\127\12\7\14\0\3\7"+
    "\1\0\11\7\1\130\15\7\14\0\3\7\1\0\2\7"+
    "\1\131\24\7\14\0\3\7\1\0\7\7\1\132\17\7"+
    "\14\0\3\7\1\0\3\7\1\133\23\7\14\0\3\7"+
    "\1\0\14\7\1\134\12\7\14\0\3\7\1\0\5\7"+
    "\1\135\21\7\14\0\3\7\1\0\7\7\1\136\17\7"+
    "\14\0\3\7\1\0\12\7\1\137\14\7\14\0\3\7"+
    "\1\0\12\7\1\140\14\7\14\0\3\7\1\0\5\7"+
    "\1\141\21\7\14\0\3\7\1\0\3\7\1\142\23\7"+
    "\14\0\3\7\1\0\21\7\1\143\5\7\14\0\3\7"+
    "\1\0\3\7\1\144\23\7\14\0\3\7\1\0\3\7"+
    "\1\145\23\7\14\0\3\7\1\0\4\7\1\146\22\7"+
    "\14\0\3\7\1\0\24\7\1\147\2\7\14\0\3\7"+
    "\1\0\15\7\1\150\11\7\14\0\3\7\1\0\6\7"+
    "\1\151\20\7\14\0\3\7\1\0\6\7\1\152\20\7"+
    "\14\0\3\7\1\0\22\7\1\153\4\7\14\0\3\7"+
    "\1\0\17\7\1\154\7\7\14\0\3\7\1\0\5\7"+
    "\1\155\21\7\14\0\3\7\1\0\5\7\1\156\21\7"+
    "\14\0\3\7\1\0\7\7\1\157\17\7\6\0\3\160"+
    "\2\0\1\160\3\161\1\160\27\161\6\160\13\0\1\162"+
    "\41\0\3\7\1\0\1\7\1\163\25\7\31\0\1\164"+
    "\31\0\3\7\1\0\11\7\1\165\15\7\34\0\1\166"+
    "\26\0\3\7\1\0\14\7\1\167\12\7\6\0\3\170"+
    "\2\0\45\170\2\0\1\170\3\171\1\170\27\171\6\170"+
    "\22\0\1\172\32\0\3\7\1\0\10\7\1\173\16\7"+
    "\41\0\1\174\21\0\3\7\1\0\21\7\1\175\5\7"+
    "\32\0\1\176\30\0\3\7\1\0\12\7\1\177\14\7"+
    "\25\0\1\200\35\0\3\7\1\0\5\7\1\201\21\7"+
    "\34\0\1\202\26\0\3\7\1\0\14\7\1\203\12\7"+
    "\22\0\1\204\40\0\3\7\1\0\2\7\1\205\24\7"+
    "\25\0\1\206\35\0\3\7\1\0\5\7\1\207\21\7"+
    "\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4056];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\2\11\2\1\2\11\20\1\1\11"+
    "\2\1\2\11\1\1\1\0\23\1\3\11\1\0\67\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Minijava(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Caractere ilegal! " + yytext() + " na linha: " + yyline + ", coluna: " + yycolumn);
            }
          case 34: break;
          case 2: 
            { /*ignora*/
            }
          case 35: break;
          case 3: 
            { System.out.print(yytext());
            }
          case 36: break;
          case 4: 
            { System.out.println("Operador MULT: "+ yytext());
            }
          case 37: break;
          case 5: 
            { System.out.println("Identificador: "+ yytext());
            }
          case 38: break;
          case 6: 
            { System.out.println("Inteiro: "+ yytext());
            }
          case 39: break;
          case 7: 
            { System.out.println("Delimitadores/pontuacao: "+ yytext());
            }
          case 40: break;
          case 8: 
            { System.out.println("Operador <: "+ yytext());
            }
          case 41: break;
          case 9: 
            { System.out.println("Operador NEGACAO: "+ yytext());
            }
          case 42: break;
          case 10: 
            { System.out.println("Operador SOMA: "+ yytext());
            }
          case 43: break;
          case 11: 
            { System.out.println("Operador SUBTRACAO: "+ yytext());
            }
          case 44: break;
          case 12: 
            { System.out.println("Palavra reservada IF: "+ yytext());
            }
          case 45: break;
          case 13: 
            { System.out.println("Operador AND: "+ yytext());
            }
          case 46: break;
          case 14: 
            { System.out.println("Operador ==: "+ yytext());
            }
          case 47: break;
          case 15: 
            { System.out.println("Operador !=: "+ yytext());
            }
          case 48: break;
          case 16: 
            { System.out.println("Palavra reservada NEW: "+ yytext());
            }
          case 49: break;
          case 17: 
            { System.out.println("Palavra reservada INT: "+ yytext());
            }
          case 50: break;
          case 18: 
            { System.out.println("Palavra reservada ELSE: "+ yytext());
            }
          case 51: break;
          case 19: 
            { System.out.println("Palavra reservada TRUE: "+ yytext());
            }
          case 52: break;
          case 20: 
            { System.out.println("Palavra reservada THIS: "+ yytext());
            }
          case 53: break;
          case 21: 
            { System.out.println("Palavra reservada VOID: "+ yytext());
            }
          case 54: break;
          case 22: 
            { System.out.println("Palavra reservada MAIN: "+ yytext());
            }
          case 55: break;
          case 23: 
            { System.out.println("Palavra reservada CLASS: "+ yytext());
            }
          case 56: break;
          case 24: 
            { System.out.println("Palavra reservada WHILE: "+ yytext());
            }
          case 57: break;
          case 25: 
            { System.out.println("Palavra reservada FALSE: "+ yytext());
            }
          case 58: break;
          case 26: 
            { System.out.println("Palavra reservada LENGTH: "+ yytext());
            }
          case 59: break;
          case 27: 
            { System.out.println("Palavra reservada STATIC: "+ yytext());
            }
          case 60: break;
          case 28: 
            { System.out.println("Palavra reservada PUBLIC: "+ yytext());
            }
          case 61: break;
          case 29: 
            { System.out.println("Palavra reservada STRING: "+ yytext());
            }
          case 62: break;
          case 30: 
            { System.out.println("Palavra reservada RETURN: "+ yytext());
            }
          case 63: break;
          case 31: 
            { System.out.println("Palavra reservada BOOLEAN: "+ yytext());
            }
          case 64: break;
          case 32: 
            { System.out.println("Palavra reservada EXTENDS: "+ yytext());
            }
          case 65: break;
          case 33: 
            { System.out.println("Palavra reservada SYSTEM.OUT.PRINTLN: "+ yytext());
            }
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Minijava [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Minijava scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Minijava(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
